services:
  - type: web
    name: pr-review-engine
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GITHUB_APP_ID
        sync: false
      - key: GITHUB_APP_PRIVATE_KEY_B64
        sync: false
      - key: GITHUB_WEBHOOK_SECRET
        sync: false
      - key: GITHUB_TARGET_REPO
        sync: false
      - key: LLM_PROVIDER
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: LLM_MODEL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        sync: false
      - key: GITHUB_MODELS_TOKEN
        sync: false
      - key: GITHUB_MODELS_MODEL
        sync: false
