"""Generate guide/reference/*.md from the code, so documentation cannot drift.

    uv run python -m scripts.gen_docs

THE ONE RULE. Every generator here reads CLASS-LEVEL metadata and module
constants -- Settings.model_fields, OPERATIONAL_KEYS, pricing._RATES,
deploy.CHECKS -- and NEVER app.config.settings. model_fields carries each
field's DECLARED DEFAULT; the settings instance carries this machine's real
DATABASE_URL, API keys, and service-account material. Everything written here
is committed and published, so reading the instance would publish those
values. Import the Settings CLASS only; the module-level instance in
app/config.py must never be imported here. tests/test_gen_docs.py pins this
both behaviourally and by parsing this module's own import statements.

Output must be DETERMINISTIC -- no timestamps, no unordered iteration, no
absolute paths. The CI drift job compares byte-for-byte, so any run-to-run
variation is a permanently red build rather than a useful signal.
"""

from __future__ import annotations

from app.config import OPERATIONAL_KEYS, Settings

GENERATED_HEADER = (
    "<!-- generated by scripts.gen_docs -- do not edit by hand.\n"
    "     Change the code it reads, then run: uv run python -m scripts.gen_docs -->\n"
)


def _type_name(annotation: object) -> str:
    """A readable type for the table. str(annotation) renders unions as
    'float | None' already; the getattr picks the friendlier name for plain
    classes ('int', not "<class 'int'>")."""
    return getattr(annotation, "__name__", None) or str(annotation)


def _default_text(field) -> str:
    """The DECLARED default -- class-level, never a configured value."""
    default = field.default
    if default is None:
        return "`None`"
    if default == "":
        return "*(empty)*"
    return f"`{default}`"


def render_config() -> str:
    """Every Settings field, and which of the two config files it belongs in.

    Secret-by-default, exactly as app/config.py's OPERATIONAL_KEYS defines it:
    a name on that list is operational and lives in .env.config; everything
    else is a credential and lives in .env.
    """
    lines = [
        GENERATED_HEADER,
        "# Configuration reference\n",
        "Every setting this service reads. `.env.config` holds operational "
        "settings and is safe to open and edit; `.env` holds credentials and "
        "nothing else.\n",
        "| Setting | Type | Default | Lives in |",
        "| --- | --- | --- | --- |",
    ]
    for name, field in Settings.model_fields.items():
        env_name = name.upper()
        home = ".env.config" if env_name in OPERATIONAL_KEYS else ".env"
        lines.append(
            f"| `{env_name}` | `{_type_name(field.annotation)}` | "
            f"{_default_text(field)} | `{home}` |"
        )
    return "\n".join(lines) + "\n"
